# Generated by Django 4.2 on 2023-04-11 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Candidatos",
            fields=[
                ("id_cand", models.IntegerField(primary_key=True, serialize=False)),
                ("candidato_nombre", models.CharField(max_length=255)),
                ("lista_nombre", models.CharField(max_length=255)),
                ("partido", models.CharField(max_length=255)),
            ],
            options={"db_table": "candidatos",},
        ),
        migrations.CreateModel(
            name="Mesas",
            fields=[
                ("mesa", models.IntegerField(primary_key=True, serialize=False)),
                ("circuito", models.CharField(max_length=255)),
                ("distrito", models.CharField(max_length=255)),
            ],
            options={"db_table": "mesas",},
        ),
        migrations.CreateModel(
            name="Escrutinio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("votos", models.IntegerField()),
                (
                    "id_candidato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="elecciones.candidatos",
                    ),
                ),
                (
                    "mesa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="elecciones.mesas",
                    ),
                ),
            ],
            options={"db_table": "escrutinio",},
        ),
    ]
