# Generated by Django 4.2 on 2023-04-11 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("elecciones", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(name="candidatos", options={"managed": False},),
        migrations.AlterModelOptions(name="escrutinio", options={"managed": False},),
        migrations.AlterModelOptions(name="mesas", options={"managed": False},),
    ]
